<template>
  <div class="loadingio-spinner-dual-ring-t88ekaixvg">
    <div class="ldio-te5mz05i7u">
      <div></div>
      <div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<style>
  @keyframes ldio-te5mz05i7u {
    0% { transform: rotate(0) }
    100% { transform: rotate(360deg) }
  }
  .ldio-te5mz05i7u div { box-sizing: border-box!important }
  .ldio-te5mz05i7u > div {
    position: absolute;
    width: 144px;
    height: 144px;
    top: 28px;
    left: 28px;
    border-radius: 50%;
    border: 16px solid #000;
    border-color: #456caa transparent #456caa transparent;
    animation: ldio-te5mz05i7u 1s linear infinite;
  }
  .ldio-te5mz05i7u > div:nth-child(2) { border-color: transparent }
  .ldio-te5mz05i7u > div:nth-child(2) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
  }
  .ldio-te5mz05i7u > div:nth-child(2) div:before, .ldio-te5mz05i7u > div:nth-child(2) div:after { 
    content: "";
    display: block;
    position: absolute;
    width: 16px;
    height: 16px;
    top: -16px;
    left: 48px;
    background: #456caa;
    border-radius: 50%;
    box-shadow: 0 128px 0 0 #456caa;
  }
  .ldio-te5mz05i7u > div:nth-child(2) div:after { 
    left: -16px;
    top: 48px;
    box-shadow: 128px 0 0 0 #456caa;
  }
  .loadingio-spinner-dual-ring-t88ekaixvg {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-te5mz05i7u {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-te5mz05i7u div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>